on: 
  push:
    branches:
      - dev
      - tests
  
  pull_request:
    branches :
      - dev
      - tests

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Action Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18.x

      # - name: Install dependencies
      #   run: npm install
      
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
          
 #     - name: install, build, test
 #       run: |
 #         npm install
 #         npm run build
 #         npm run test
